services:
  database:
    image: mariadb
    container_name: mariadb-container
    restart: unless-stopped
    volumes:
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/mysql
    env_file:
      - ../../.env.development
    ports:
      - '3306:3306'

  cypress:
    image: 'cypress/included:13.6.1'

volumes:
  data:
